apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: krishna
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"